# Generated by Django 5.2.13 on 2026-05-04 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annotation_platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('SeriesInstanceUID', models.CharField(max_length=255, unique=True)),
                ('SeriesDescription', models.CharField(blank=True, max_length=255, null=True)),
                ('SeriesNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('Modality', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('PatientID', models.CharField(max_length=255, unique=True)),
                ('PatientName', models.CharField(blank=True, max_length=255, null=True)),
                ('PatientAge', models.CharField(blank=True, max_length=255, null=True)),
                ('PatientSex', models.CharField(blank=True, max_length=255, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation_platform.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('SOPInstanceUID', models.CharField(max_length=255, unique=True)),
                ('InstanceNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('NumberOfFrames', models.CharField(blank=True, max_length=255, null=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dicom_manager.series')),
            ],
        ),
        migrations.CreateModel(
            name='AnnotationSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dicom_manager.series')),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('StudyInstanceUID', models.CharField(max_length=255, unique=True)),
                ('AccessionNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('StudyDescription', models.CharField(blank=True, max_length=255, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dicom_manager.patient')),
            ],
        ),
        migrations.AddField(
            model_name='series',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dicom_manager.study'),
        ),
    ]
