# Generated by Django 5.2.13 on 2026-05-04 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annotation_platform', '0001_initial'),
        ('dicom_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='patients',
            field=models.ManyToManyField(blank=True, related_name='projects', to='dicom_manager.patient'),
        ),
        migrations.AddField(
            model_name='projectuserpatientsassignment',
            name='patients',
            field=models.ManyToManyField(related_name='project_user_patients_assignments', to='dicom_manager.patient'),
        ),
        migrations.AddField(
            model_name='projectuserpatientsassignment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_user_patients_assignments', to='annotation_platform.project'),
        ),
        migrations.AddField(
            model_name='projectuserpatientsassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation_platform.workspace'),
        ),
        migrations.AddConstraint(
            model_name='projectuserpatientsassignment',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='unique_project_user_patients_assignment'),
        ),
    ]
