"""
Django settings for annotation_platform project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os


def get_bool(env_var, default):
    return os.getenv(env_var, default).strip().strip('"').lower() in (
        "true",
        "1",
        "yes",
    )


def get_list(env_var, default=""):
    return [item for item in os.getenv(env_var, default).split(",") if item]


# Environment variables
APP_ENV = os.getenv("APP_ENV", "production").strip().strip('"').lower()
DEVELOPMENT_MODE = APP_ENV == "development"

DATABASE_HOST = os.getenv(
    "DATABASE_HOST", "127.0.0.1" if DEVELOPMENT_MODE else ""
)
DATABASE_PORT = os.getenv("DATABASE_PORT", "5432" if DEVELOPMENT_MODE else "")
DATABASE_NAME = os.getenv(
    "DATABASE_NAME", "annotation_platform" if DEVELOPMENT_MODE else ""
)
DATABASE_USER = os.getenv(
    "DATABASE_USER", "annotation_platform" if DEVELOPMENT_MODE else ""
)
DATABASE_PASSWORD = os.getenv(
    "DATABASE_PASSWORD", "annotation_platform" if DEVELOPMENT_MODE else ""
)
DATABASE_SSLMODE = os.getenv(
    "DATABASE_SSLMODE", "disable" if DEVELOPMENT_MODE else "require"
)

ALLOWED_HOSTS = get_list(
    "ALLOWED_HOSTS", "localhost,127.0.0.1" if DEVELOPMENT_MODE else ""
)
CORS_ALLOWED_ORIGINS = get_list(
    "CORS_ALLOWED_ORIGINS",
    (
        "http://localhost:5173,http://127.0.0.1:5173"
        if DEVELOPMENT_MODE
        else ""
    ),
)

CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS.copy()

SESSION_COOKIE_SAMESITE = (
    os.getenv(
        "SESSION_COOKIE_SAMESITE", "Lax" if DEVELOPMENT_MODE else "None"
    )
    .strip()
    .strip('"')
)
CSRF_COOKIE_SAMESITE = (
    os.getenv("CSRF_COOKIE_SAMESITE", "Lax" if DEVELOPMENT_MODE else "None")
    .strip()
    .strip('"')
)
SESSION_COOKIE_SECURE = get_bool("SESSION_COOKIE_SECURE", "False")
CSRF_COOKIE_SECURE = get_bool("CSRF_COOKIE_SECURE", "False")

AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID", "")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY", "")
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME", "")
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "")
AWS_S3_ENDPOINT_URL = os.getenv("AWS_S3_ENDPOINT_URL", "")
AWS_S3_SIGNATURE_VERSION = os.getenv("AWS_S3_SIGNATURE_VERSION", "")

SEGMENTATION_MAX_UPLOAD_BYTES = int(
    os.getenv("SEGMENTATION_MAX_UPLOAD_BYTES", str(256 * 1024 * 1024))
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-development-only" if DEVELOPMENT_MODE else "",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_bool("DEBUG", "True" if DEVELOPMENT_MODE else "False")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "django_extensions",
    "annotation_platform",
    "authentication",
    "dicom_manager",
    "storages",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "annotation_platform.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "annotation_platform.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "HOST": DATABASE_HOST,
        "PORT": DATABASE_PORT,
        "NAME": DATABASE_NAME,
        "USER": DATABASE_USER,
        "PASSWORD": DATABASE_PASSWORD,
        "OPTIONS": {
            "sslmode": DATABASE_SSLMODE,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
}

LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO").strip().strip('"').upper()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "console": {
            "format": "%(levelname)s %(name)s: %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "console",
        },
    },
    "loggers": {
        "annotation_platform": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "authentication": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "dicom_manager": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}

STORAGE_BACKEND = os.getenv(
    "STORAGE_BACKEND", "local" if DEVELOPMENT_MODE else "s3"
).lower()
if STORAGE_BACKEND not in {"local", "s3"}:
    raise ValueError("STORAGE_BACKEND must be either 'local' or 's3'")

MEDIA_ROOT = Path(os.getenv("MEDIA_ROOT", str(BASE_DIR / "media")))
MEDIA_URL = os.getenv("MEDIA_URL", "/media/")
LOCAL_MEDIA_BASE_URL = os.getenv(
    "LOCAL_MEDIA_BASE_URL", "http://localhost:8000/media/"
)

if STORAGE_BACKEND == "local":
    DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
else:
    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

AUTH_USER_MODEL = "authentication.User"
